name: Run runreport.py

on:
  workflow_dispatch:

jobs:
  run_process_stock_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run process_stock_data function
        run: |
          python -c "
import sys
import traceback
from BackEnd.runreport import process_stock_data
from datetime import datetime

try:
    process_stock_data(datetime.now())
    print('Process completed successfully.')
except Exception as e:
    print(f'An error occurred: {e}')
    traceback.print_exc()
    sys.exit(1)
          "
