name: Run runreport.py

on:
  schedule:
    - cron: '0 3 * * *'  # Trigger the workflow daily at 3:00 AM UTC
  workflow_dispatch:  # Allows manual trigger of the workflow

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v3  # Checkout the repository content to GitHub runner

  setup_python:
    runs-on: ubuntu-latest
    needs: checkout  # This job depends on the checkout job
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # Install the Python version needed

  install_dependencies:
    runs-on: ubuntu-latest
    needs: setup_python  # This job depends on the setup_python job
    steps:
      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  run_backend_code:
    runs-on: ubuntu-latest
    needs: install_dependencies  # This job depends on the install_dependencies job
    steps:
      - name: Run Backend code
        run: python -c "from BackEnd.runreport import process_stock_data; from datetime import datetime; process_stock_data()"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Provide GitHub token to the script

  check_output:
    runs-on: ubuntu-latest
    needs: run_backend_code  # This job depends on the run_backend_code job
    steps:
      - name: Check output
        run: |
          echo "Checking if the previous step completed successfully"
          if [ $? -eq 0 ]; then
            echo "Process completed successfully."
          else
            echo "The process failed."
            exit 1
